// feat_115.mqh  — bos_time
// Auto-generated by gen_feat_mqh.py  (feature index 115)
// Python: features.py BASE_FEATURE_COLS[115] = "bos_time"
#ifndef FEAT_115_MQH
#define FEAT_115_MQH



double CalcFeat_115(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{
   return 0.0;
}

#endif // FEAT_115_MQH
