// feat_016.mqh  — sma_100
// Auto-generated by gen_feat_mqh.py  (feature index 16)
// Python: features.py BASE_FEATURE_COLS[16] = "sma_100"
#ifndef FEAT_016_MQH
#define FEAT_016_MQH



double CalcFeat_016(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double sum = 0.0;
   int cnt = 0;
   for(int k = i; k < i + 100 && k < needed; k++) { sum += close[k]; cnt++; }
   return (cnt > 0) ? sum / cnt : close[i];
}

#endif // FEAT_016_MQH
