// feat_205.mqh  — price_diff_75
// Auto-generated by gen_feat_mqh.py  (feature index 205)
// Python: features.py BASE_FEATURE_COLS[205] = "price_diff_75"
#ifndef FEAT_205_MQH
#define FEAT_205_MQH



double CalcFeat_205(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+75<needed)?close[i]-close[i+75]:0.0;
}

#endif // FEAT_205_MQH
