// feat_188.mqh  — momentum_50
// Auto-generated by gen_feat_mqh.py  (feature index 188)
// Python: features.py BASE_FEATURE_COLS[188] = "momentum_50"
#ifndef FEAT_188_MQH
#define FEAT_188_MQH



double CalcFeat_188(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+50<needed)?close[i]-close[i+50]:0.0;
}

#endif // FEAT_188_MQH
