// feat_191.mqh  — momentum_55
// Auto-generated by gen_feat_mqh.py  (feature index 191)
// Python: features.py BASE_FEATURE_COLS[191] = "momentum_55"
#ifndef FEAT_191_MQH
#define FEAT_191_MQH



double CalcFeat_191(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+55<needed)?close[i]-close[i+55]:0.0;
}

#endif // FEAT_191_MQH
