// feat_137.mqh  — ret1_15
// Auto-generated by gen_feat_mqh.py  (feature index 137)
// Python: features.py BASE_FEATURE_COLS[137] = "ret1_15"
#ifndef FEAT_137_MQH
#define FEAT_137_MQH



double CalcFeat_137(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+15<needed)?close[i+15]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_137_MQH
