// feat_052.mqh  — ndi_14
// Auto-generated by gen_feat_mqh.py  (feature index 52)
// Python: features.py BASE_FEATURE_COLS[52] = "ndi_14"
#ifndef FEAT_052_MQH
#define FEAT_052_MQH



double CalcFeat_052(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double alpha=1.0/14.0;
   double rm_tr=high[needed-1]-low[needed-1];
   double rm_ndm=0;
   for(int k=needed-2;k>=i;k--){
      double hl=high[k]-low[k];
      double hpc=MathAbs(high[k]-close[k+1]);
      double lpc=MathAbs(low[k]-close[k+1]);
      double tr=MathMax(hl,MathMax(hpc,lpc));
      rm_tr=alpha*tr+(1-alpha)*rm_tr;
      double up_m=high[k]-high[k+1];
      double dn_m=low[k+1]-low[k];
      double ndm=(dn_m>up_m&&dn_m>0)?dn_m:0.0;
      rm_ndm=alpha*ndm+(1-alpha)*rm_ndm;
   }
   return 100*rm_ndm/(rm_tr+1e-9)/100.0;
}

#endif // FEAT_052_MQH
