// feat_211.mqh  — price_diff_85
// Auto-generated by gen_feat_mqh.py  (feature index 211)
// Python: features.py BASE_FEATURE_COLS[211] = "price_diff_85"
#ifndef FEAT_211_MQH
#define FEAT_211_MQH



double CalcFeat_211(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+85<needed)?close[i]-close[i+85]:0.0;
}

#endif // FEAT_211_MQH
