// feat_089.mqh  — roll_mean_20
// Auto-generated by gen_feat_mqh.py  (feature index 89)
// Python: features.py BASE_FEATURE_COLS[89] = "roll_mean_20"
#ifndef FEAT_089_MQH
#define FEAT_089_MQH



double CalcFeat_089(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<20&&i+k<needed;k++){s+=close[i+k];c2++;}
   return (c2>0)?s/c2:close[i];
}

#endif // FEAT_089_MQH
