// feat_157.mqh  — vol_45
// Auto-generated by gen_feat_mqh.py  (feature index 157)
// Python: features.py BASE_FEATURE_COLS[157] = "vol_45"
#ifndef FEAT_157_MQH
#define FEAT_157_MQH



double CalcFeat_157(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<45&&i+k<needed;k++){s+=vol[i+k];c2++;}
   return (c2>0)?s/c2:0;
}

#endif // FEAT_157_MQH
