// feat_105.mqh  — is_bear_engulf
// Auto-generated by gen_feat_mqh.py  (feature index 105)
// Python: features.py BASE_FEATURE_COLS[105] = "is_bear_engulf"
#ifndef FEAT_105_MQH
#define FEAT_105_MQH



double CalcFeat_105(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   if(!(i+1<needed)) return 0.0;
   double body_cur=close[i]-open[i];
   double body_prv=close[i+1]-open[i+1];
   return (body_cur<0&&body_prv>0&&open[i]>=close[i+1]&&close[i]<=open[i+1])?1.0:0.0;
}

#endif // FEAT_105_MQH
