// feat_117.mqh  — bos_fibo_zone
// Auto-generated by gen_feat_mqh.py  (feature index 117)
// Python: features.py BASE_FEATURE_COLS[117] = "bos_fibo_zone"
#ifndef FEAT_117_MQH
#define FEAT_117_MQH



double CalcFeat_117(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{
   return 0.0;
}

#endif // FEAT_117_MQH
