// feat_106.mqh  — is_hammer
// Auto-generated by gen_feat_mqh.py  (feature index 106)
// Python: features.py BASE_FEATURE_COLS[106] = "is_hammer"
#ifndef FEAT_106_MQH
#define FEAT_106_MQH



double CalcFeat_106(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double body=MathAbs(close[i]-open[i]);
   double lower=MathMin(close[i],open[i])-low[i];
   double upper=high[i]-MathMax(close[i],open[i]);
   return (lower>body*2&&upper<body*0.5)?1.0:0.0;
}

#endif // FEAT_106_MQH
