// feat_116.mqh  — bos_pips
// Auto-generated by gen_feat_mqh.py  (feature index 116)
// Python: features.py BASE_FEATURE_COLS[116] = "bos_pips"
#ifndef FEAT_116_MQH
#define FEAT_116_MQH



double CalcFeat_116(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{
   return 0.0;
}

#endif // FEAT_116_MQH
