// feat_001.mqh  — ema_5
// Auto-generated by gen_feat_mqh.py  (feature index 1)
// Python: features.py BASE_FEATURE_COLS[1] = "ema_5"
#ifndef FEAT_001_MQH
#define FEAT_001_MQH



double CalcFeat_001(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double alpha = 2.0 / (5.0 + 1.0);
   double em = close[needed-1];
   for(int k = needed-2; k >= i; k--)
      em = alpha * close[k] + (1.0 - alpha) * em;
   return em;
}

#endif // FEAT_001_MQH
