// feat_149.mqh  — ret1_35
// Auto-generated by gen_feat_mqh.py  (feature index 149)
// Python: features.py BASE_FEATURE_COLS[149] = "ret1_35"
#ifndef FEAT_149_MQH
#define FEAT_149_MQH



double CalcFeat_149(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+35<needed)?close[i+35]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_149_MQH
