// feat_111.mqh  — ll
// Auto-generated by gen_feat_mqh.py  (feature index 111)
// Python: features.py BASE_FEATURE_COLS[111] = "ll"
#ifndef FEAT_111_MQH
#define FEAT_111_MQH



double CalcFeat_111(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{
   return (i+1<needed&&low[i]<low[i+1])?1.0:0.0;
}

#endif // FEAT_111_MQH
