// feat_227.mqh  — momentum_115
// Auto-generated by gen_feat_mqh.py  (feature index 227)
// Python: features.py BASE_FEATURE_COLS[227] = "momentum_115"
#ifndef FEAT_227_MQH
#define FEAT_227_MQH



double CalcFeat_227(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+115<needed)?close[i]-close[i+115]:0.0;
}

#endif // FEAT_227_MQH
