// feat_007.mqh  — wma_10
// Auto-generated by gen_feat_mqh.py  (feature index 7)
// Python: features.py BASE_FEATURE_COLS[7] = "wma_10"
#ifndef FEAT_007_MQH
#define FEAT_007_MQH



double CalcFeat_007(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double num = 0.0, den = 0.0;
   for(int k = 0; k < 10 && i+k < needed; k++) {
      double w = (double)(10 - k);
      num += close[i+k] * w;
      den += w;
   }
   return (den > 0) ? num/den : close[i];
}

#endif // FEAT_007_MQH
