// feat_124.mqh  — hour_cos
// Auto-generated by gen_feat_mqh.py  (feature index 124)
// Python: features.py BASE_FEATURE_COLS[124] = "hour_cos"
#ifndef FEAT_124_MQH
#define FEAT_124_MQH

// Requires GetBarTime(int i) defined in main EA

double CalcFeat_124(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   MqlDateTime mdt; TimeToStruct(GetBarTime(i),mdt);
   int hr=mdt.hour;
   
   
   return MathCos(2.0*M_PI*hr/24.0);
   
   
   
   
   
   
}

#endif // FEAT_124_MQH
