// feat_015.mqh  — wma_50
// Auto-generated by gen_feat_mqh.py  (feature index 15)
// Python: features.py BASE_FEATURE_COLS[15] = "wma_50"
#ifndef FEAT_015_MQH
#define FEAT_015_MQH



double CalcFeat_015(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double num = 0.0, den = 0.0;
   for(int k = 0; k < 50 && i+k < needed; k++) {
      double w = (double)(50 - k);
      num += close[i+k] * w;
      den += w;
   }
   return (den > 0) ? num/den : close[i];
}

#endif // FEAT_015_MQH
