// feat_032.mqh  — rsi_28
// Auto-generated by gen_feat_mqh.py  (feature index 32)
// Python: features.py BASE_FEATURE_COLS[32] = "rsi_28"
#ifndef FEAT_032_MQH
#define FEAT_032_MQH



double CalcFeat_032(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double alpha=1.0/28.0;
   double ag=0,al=0;
   ag=al=0;
   int inited=0;
   for(int k=needed-2;k>=i;k--){
      double d=close[k]-close[k+1];
      double g=(d>0)?d:0.0, l=(d<0)?-d:0.0;
      if(!inited){ag=g;al=l;inited=1;} else {ag=alpha*g+(1-alpha)*ag; al=alpha*l+(1-alpha)*al;}
   }
   double rs=ag/(al+1e-9);
   return (100.0 - 100.0/(1.0+rs))/100.0;
}

#endif // FEAT_032_MQH
