// feat_065.mqh  — s1
// Auto-generated by gen_feat_mqh.py  (feature index 65)
// Python: features.py BASE_FEATURE_COLS[65] = "s1"
#ifndef FEAT_065_MQH
#define FEAT_065_MQH



double CalcFeat_065(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   if(i+1>=needed) return close[i];
   double pp=(high[i+1]+low[i+1]+close[i+1])/3.0;
   return 2*pp-high[i+1];
}

#endif // FEAT_065_MQH
