// feat_152.mqh  — ret1_40
// Auto-generated by gen_feat_mqh.py  (feature index 152)
// Python: features.py BASE_FEATURE_COLS[152] = "ret1_40"
#ifndef FEAT_152_MQH
#define FEAT_152_MQH



double CalcFeat_152(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+40<needed)?close[i+40]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_152_MQH
