// feat_040.mqh  — bb_width_20
// Auto-generated by gen_feat_mqh.py  (feature index 40)
// Python: features.py BASE_FEATURE_COLS[40] = "bb_width_20"
#ifndef FEAT_040_MQH
#define FEAT_040_MQH



double CalcFeat_040(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<20&&i+k<needed;k++){s+=close[i+k];c2++;}
   double m=(c2>0)?s/c2:close[i];
   double sq=0;
   for(int k=0;k<20&&i+k<needed;k++){double d=close[i+k]-m;sq+=d*d;}
   double std=MathSqrt((c2>0)?sq/c2:0);
   double up=m+2*std, dn=m-2*std;
   double rng=up-dn;
   return (m>1e-9)?rng/m:0.0;
}

#endif // FEAT_040_MQH
