// feat_148.mqh  — vol_30
// Auto-generated by gen_feat_mqh.py  (feature index 148)
// Python: features.py BASE_FEATURE_COLS[148] = "vol_30"
#ifndef FEAT_148_MQH
#define FEAT_148_MQH



double CalcFeat_148(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<30&&i+k<needed;k++){s+=vol[i+k];c2++;}
   return (c2>0)?s/c2:0;
}

#endif // FEAT_148_MQH
