// feat_196.mqh  — price_diff_60
// Auto-generated by gen_feat_mqh.py  (feature index 196)
// Python: features.py BASE_FEATURE_COLS[196] = "price_diff_60"
#ifndef FEAT_196_MQH
#define FEAT_196_MQH



double CalcFeat_196(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+60<needed)?close[i]-close[i+60]:0.0;
}

#endif // FEAT_196_MQH
