// feat_138.mqh  — ret5_15
// Auto-generated by gen_feat_mqh.py  (feature index 138)
// Python: features.py BASE_FEATURE_COLS[138] = "ret5_15"
#ifndef FEAT_138_MQH
#define FEAT_138_MQH



double CalcFeat_138(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+5<needed)?close[i+5]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_138_MQH
