// feat_053.mqh  — cci_14
// Auto-generated by gen_feat_mqh.py  (feature index 53)
// Python: features.py BASE_FEATURE_COLS[53] = "cci_14"
#ifndef FEAT_053_MQH
#define FEAT_053_MQH



double CalcFeat_053(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double tp=(high[i]+low[i]+close[i])/3.0;
   double s=0; int c2=14;
   for(int k=0;k<14&&i+k<needed;k++) s+=(high[i+k]+low[i+k]+close[i+k])/3.0;
   double m=s/c2;
   double mad=0;
   for(int k=0;k<14&&i+k<needed;k++) mad+=MathAbs((high[i+k]+low[i+k]+close[i+k])/3.0-m);
   mad/=c2;
   return (tp-m)/(0.015*mad+1e-9)/100.0;
}

#endif // FEAT_053_MQH
