// feat_125.mqh  — dow_sin
// Auto-generated by gen_feat_mqh.py  (feature index 125)
// Python: features.py BASE_FEATURE_COLS[125] = "dow_sin"
#ifndef FEAT_125_MQH
#define FEAT_125_MQH

// Requires GetBarTime(int i) defined in main EA

double CalcFeat_125(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   MqlDateTime mdt; TimeToStruct(GetBarTime(i),mdt);
   int hr=mdt.hour;
   int dow=mdt.day_of_week;
   
   
   return MathSin(2.0*M_PI*dow/5.0);
   
   
   
   
   
}

#endif // FEAT_125_MQH
