// feat_192.mqh  — volatility_55
// Auto-generated by gen_feat_mqh.py  (feature index 192)
// Python: features.py BASE_FEATURE_COLS[192] = "volatility_55"
#ifndef FEAT_192_MQH
#define FEAT_192_MQH



double CalcFeat_192(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0;int c2=0;
   for(int k=0;k<55&&i+k<needed;k++){s+=close[i+k];c2++;}
   double m=(c2>0)?s/c2:close[i];
   double sq=0;
   for(int k=0;k<55&&i+k<needed;k++){double d=close[i+k]-m;sq+=d*d;}
   return MathSqrt((c2>0)?sq/c2:0);
}

#endif // FEAT_192_MQH
