// feat_011.mqh  — wma_20
// Auto-generated by gen_feat_mqh.py  (feature index 11)
// Python: features.py BASE_FEATURE_COLS[11] = "wma_20"
#ifndef FEAT_011_MQH
#define FEAT_011_MQH



double CalcFeat_011(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double num = 0.0, den = 0.0;
   for(int k = 0; k < 20 && i+k < needed; k++) {
      double w = (double)(20 - k);
      num += close[i+k] * w;
      den += w;
   }
   return (den > 0) ? num/den : close[i];
}

#endif // FEAT_011_MQH
