// feat_133.mqh  — vol_5
// Auto-generated by gen_feat_mqh.py  (feature index 133)
// Python: features.py BASE_FEATURE_COLS[133] = "vol_5"
#ifndef FEAT_133_MQH
#define FEAT_133_MQH



double CalcFeat_133(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<5&&i+k<needed;k++){s+=vol[i+k];c2++;}
   return (c2>0)?s/c2:0;
}

#endif // FEAT_133_MQH
