// feat_057.mqh  — pdi_28
// Auto-generated by gen_feat_mqh.py  (feature index 57)
// Python: features.py BASE_FEATURE_COLS[57] = "pdi_28"
#ifndef FEAT_057_MQH
#define FEAT_057_MQH



double CalcFeat_057(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double alpha=1.0/28.0;
   double rm_tr=high[needed-1]-low[needed-1];
   double rm_pdm=0;
   for(int k=needed-2;k>=i;k--){
      double hl=high[k]-low[k];
      double hpc=MathAbs(high[k]-close[k+1]);
      double lpc=MathAbs(low[k]-close[k+1]);
      double tr=MathMax(hl,MathMax(hpc,lpc));
      rm_tr=alpha*tr+(1-alpha)*rm_tr;
      double up_m=high[k]-high[k+1];
      double dn_m=low[k+1]-low[k];
      double pdm=(up_m>dn_m&&up_m>0)?up_m:0.0;
      rm_pdm=alpha*pdm+(1-alpha)*rm_pdm;
   }
   return 100*rm_pdm/(rm_tr+1e-9)/100.0;
}

#endif // FEAT_057_MQH
