// feat_127.mqh  — is_tokyo
// Auto-generated by gen_feat_mqh.py  (feature index 127)
// Python: features.py BASE_FEATURE_COLS[127] = "is_tokyo"
#ifndef FEAT_127_MQH
#define FEAT_127_MQH

// Requires GetBarTime(int i) defined in main EA

double CalcFeat_127(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   MqlDateTime mdt; TimeToStruct(GetBarTime(i),mdt);
   int hr=mdt.hour;
   
   
   
   
   
   return (hr>=0&&hr<9)?1.0:0.0;
   
   
   
}

#endif // FEAT_127_MQH
