// feat_114.mqh  — bos_bars
// Auto-generated by gen_feat_mqh.py  (feature index 114)
// Python: features.py BASE_FEATURE_COLS[114] = "bos_bars"
#ifndef FEAT_114_MQH
#define FEAT_114_MQH



double CalcFeat_114(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{
   return 0.0;
}

#endif // FEAT_114_MQH
