// feat_000.mqh  — sma_5
// Auto-generated by gen_feat_mqh.py  (feature index 0)
// Python: features.py BASE_FEATURE_COLS[0] = "sma_5"
#ifndef FEAT_000_MQH
#define FEAT_000_MQH



double CalcFeat_000(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double sum = 0.0;
   int cnt = 0;
   for(int k = i; k < i + 5 && k < needed; k++) { sum += close[k]; cnt++; }
   return (cnt > 0) ? sum / cnt : close[i];
}

#endif // FEAT_000_MQH
