// feat_068.mqh  — donchian_width_20
// Auto-generated by gen_feat_mqh.py  (feature index 68)
// Python: features.py BASE_FEATURE_COLS[68] = "donchian_width_20"
#ifndef FEAT_068_MQH
#define FEAT_068_MQH



double CalcFeat_068(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double dh=high[i],dl=low[i];
   for(int k=1;k<20&&i+k<needed;k++){dh=MathMax(dh,high[i+k]);dl=MathMin(dl,low[i+k]);}
   return (dh-dl)/(close[i]+1e-9);
}

#endif // FEAT_068_MQH
