// feat_093.mqh  — zscore_20
// Auto-generated by gen_feat_mqh.py  (feature index 93)
// Python: features.py BASE_FEATURE_COLS[93] = "zscore_20"
#ifndef FEAT_093_MQH
#define FEAT_093_MQH



double CalcFeat_093(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<20&&i+k<needed;k++){s+=close[i+k];c2++;}
   double m=(c2>0)?s/c2:close[i];
   double sq=0;
   for(int k=0;k<20&&i+k<needed;k++){double d=close[i+k]-m;sq+=d*d;}
   double std=MathSqrt((c2>0)?sq/c2:0);
   return (std>1e-12)?(close[i]-m)/std:0.0;
}

#endif // FEAT_093_MQH
