// feat_066.mqh  — s2
// Auto-generated by gen_feat_mqh.py  (feature index 66)
// Python: features.py BASE_FEATURE_COLS[66] = "s2"
#ifndef FEAT_066_MQH
#define FEAT_066_MQH



double CalcFeat_066(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   if(i+1>=needed) return close[i];
   double pp=(high[i+1]+low[i+1]+close[i+1])/3.0;
   return pp-(high[i+1]-low[i+1]);
}

#endif // FEAT_066_MQH
