// feat_170.mqh  — momentum_20
// Auto-generated by gen_feat_mqh.py  (feature index 170)
// Python: features.py BASE_FEATURE_COLS[170] = "momentum_20"
#ifndef FEAT_170_MQH
#define FEAT_170_MQH



double CalcFeat_170(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+20<needed)?close[i]-close[i+20]:0.0;
}

#endif // FEAT_170_MQH
