// feat_063.mqh  — r1
// Auto-generated by gen_feat_mqh.py  (feature index 63)
// Python: features.py BASE_FEATURE_COLS[63] = "r1"
#ifndef FEAT_063_MQH
#define FEAT_063_MQH



double CalcFeat_063(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   if(i+1>=needed) return close[i];
   double pp=(high[i+1]+low[i+1]+close[i+1])/3.0;
   return 2*pp-low[i+1];
}

#endif // FEAT_063_MQH
