// feat_182.mqh  — momentum_40
// Auto-generated by gen_feat_mqh.py  (feature index 182)
// Python: features.py BASE_FEATURE_COLS[182] = "momentum_40"
#ifndef FEAT_182_MQH
#define FEAT_182_MQH



double CalcFeat_182(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+40<needed)?close[i]-close[i+40]:0.0;
}

#endif // FEAT_182_MQH
