// feat_004.mqh  — sma_10
// Auto-generated by gen_feat_mqh.py  (feature index 4)
// Python: features.py BASE_FEATURE_COLS[4] = "sma_10"
#ifndef FEAT_004_MQH
#define FEAT_004_MQH



double CalcFeat_004(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double sum = 0.0;
   int cnt = 0;
   for(int k = i; k < i + 10 && k < needed; k++) { sum += close[k]; cnt++; }
   return (cnt > 0) ? sum / cnt : close[i];
}

#endif // FEAT_004_MQH
