// feat_119.mqh  — bos_move_pips
// Auto-generated by gen_feat_mqh.py  (feature index 119)
// Python: features.py BASE_FEATURE_COLS[119] = "bos_move_pips"
#ifndef FEAT_119_MQH
#define FEAT_119_MQH



double CalcFeat_119(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{
   return 0.0;
}

#endif // FEAT_119_MQH
