// feat_067.mqh  — donchian_pos_20
// Auto-generated by gen_feat_mqh.py  (feature index 67)
// Python: features.py BASE_FEATURE_COLS[67] = "donchian_pos_20"
#ifndef FEAT_067_MQH
#define FEAT_067_MQH



double CalcFeat_067(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double dh=high[i],dl=low[i];
   for(int k=1;k<20&&i+k<needed;k++){dh=MathMax(dh,high[i+k]);dl=MathMin(dl,low[i+k]);}
   return (close[i]-dl)/(dh-dl+1e-9);
}

#endif // FEAT_067_MQH
