// feat_158.mqh  — ret1_50
// Auto-generated by gen_feat_mqh.py  (feature index 158)
// Python: features.py BASE_FEATURE_COLS[158] = "ret1_50"
#ifndef FEAT_158_MQH
#define FEAT_158_MQH



double CalcFeat_158(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+50<needed)?close[i+50]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_158_MQH
