// feat_062.mqh  — pivot
// Auto-generated by gen_feat_mqh.py  (feature index 62)
// Python: features.py BASE_FEATURE_COLS[62] = "pivot"
#ifndef FEAT_062_MQH
#define FEAT_062_MQH



double CalcFeat_062(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   if(i+1>=needed) return close[i];
   return (high[i+1]+low[i+1]+close[i+1])/3.0;
}

#endif // FEAT_062_MQH
