// feat_121.mqh  — bos_macd_sync
// Auto-generated by gen_feat_mqh.py  (feature index 121)
// Python: features.py BASE_FEATURE_COLS[121] = "bos_macd_sync"
#ifndef FEAT_121_MQH
#define FEAT_121_MQH



double CalcFeat_121(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{
   return 0.0;
}

#endif // FEAT_121_MQH
