// feat_064.mqh  — r2
// Auto-generated by gen_feat_mqh.py  (feature index 64)
// Python: features.py BASE_FEATURE_COLS[64] = "r2"
#ifndef FEAT_064_MQH
#define FEAT_064_MQH



double CalcFeat_064(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   if(i+1>=needed) return close[i];
   double pp=(high[i+1]+low[i+1]+close[i+1])/3.0;
   return pp+(high[i+1]-low[i+1]);
}

#endif // FEAT_064_MQH
