// feat_169.mqh  — price_diff_15
// Auto-generated by gen_feat_mqh.py  (feature index 169)
// Python: features.py BASE_FEATURE_COLS[169] = "price_diff_15"
#ifndef FEAT_169_MQH
#define FEAT_169_MQH



double CalcFeat_169(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+15<needed)?close[i]-close[i+15]:0.0;
}

#endif // FEAT_169_MQH
