// feat_039.mqh  — bb_pos_20
// Auto-generated by gen_feat_mqh.py  (feature index 39)
// Python: features.py BASE_FEATURE_COLS[39] = "bb_pos_20"
#ifndef FEAT_039_MQH
#define FEAT_039_MQH



double CalcFeat_039(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<20&&i+k<needed;k++){s+=close[i+k];c2++;}
   double m=(c2>0)?s/c2:close[i];
   double sq=0;
   for(int k=0;k<20&&i+k<needed;k++){double d=close[i+k]-m;sq+=d*d;}
   double std=MathSqrt((c2>0)?sq/c2:0);
   double up=m+2*std, dn=m-2*std;
   double rng=up-dn;
   return (rng>1e-9)?(close[i]-dn)/rng:0.5;
}

#endif // FEAT_039_MQH
