// feat_199.mqh  — price_diff_65
// Auto-generated by gen_feat_mqh.py  (feature index 199)
// Python: features.py BASE_FEATURE_COLS[199] = "price_diff_65"
#ifndef FEAT_199_MQH
#define FEAT_199_MQH



double CalcFeat_199(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+65<needed)?close[i]-close[i+65]:0.0;
}

#endif // FEAT_199_MQH
