// feat_153.mqh  — ret5_40
// Auto-generated by gen_feat_mqh.py  (feature index 153)
// Python: features.py BASE_FEATURE_COLS[153] = "ret5_40"
#ifndef FEAT_153_MQH
#define FEAT_153_MQH



double CalcFeat_153(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+5<needed)?close[i+5]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_153_MQH
