// feat_129.mqh  — is_ny
// Auto-generated by gen_feat_mqh.py  (feature index 129)
// Python: features.py BASE_FEATURE_COLS[129] = "is_ny"
#ifndef FEAT_129_MQH
#define FEAT_129_MQH

// Requires GetBarTime(int i) defined in main EA

double CalcFeat_129(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   MqlDateTime mdt; TimeToStruct(GetBarTime(i),mdt);
   int hr=mdt.hour;
   
   
   
   
   
   
   
   return (hr>=13&&hr<22)?1.0:0.0;
   
}

#endif // FEAT_129_MQH
