// feat_206.mqh  — momentum_80
// Auto-generated by gen_feat_mqh.py  (feature index 206)
// Python: features.py BASE_FEATURE_COLS[206] = "momentum_80"
#ifndef FEAT_206_MQH
#define FEAT_206_MQH



double CalcFeat_206(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+80<needed)?close[i]-close[i+80]:0.0;
}

#endif // FEAT_206_MQH
