// feat_003.mqh  — wma_5
// Auto-generated by gen_feat_mqh.py  (feature index 3)
// Python: features.py BASE_FEATURE_COLS[3] = "wma_5"
#ifndef FEAT_003_MQH
#define FEAT_003_MQH



double CalcFeat_003(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double num = 0.0, den = 0.0;
   for(int k = 0; k < 5 && i+k < needed; k++) {
      double w = (double)(5 - k);
      num += close[i+k] * w;
      den += w;
   }
   return (den > 0) ? num/den : close[i];
}

#endif // FEAT_003_MQH
