// feat_154.mqh  — vol_40
// Auto-generated by gen_feat_mqh.py  (feature index 154)
// Python: features.py BASE_FEATURE_COLS[154] = "vol_40"
#ifndef FEAT_154_MQH
#define FEAT_154_MQH



double CalcFeat_154(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<40&&i+k<needed;k++){s+=vol[i+k];c2++;}
   return (c2>0)?s/c2:0;
}

#endif // FEAT_154_MQH
