// feat_100.mqh  — upper_w
// Auto-generated by gen_feat_mqh.py  (feature index 100)
// Python: features.py BASE_FEATURE_COLS[100] = "upper_w"
#ifndef FEAT_100_MQH
#define FEAT_100_MQH



double CalcFeat_100(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{
   return high[i]-MathMax(close[i],open[i]);
}

#endif // FEAT_100_MQH
