// feat_061.mqh  — psar
// Auto-generated by gen_feat_mqh.py  (feature index 61)
// Python: features.py BASE_FEATURE_COLS[61] = "psar"
#ifndef FEAT_061_MQH
#define FEAT_061_MQH



double CalcFeat_061(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{
   return close[i]; // PSAR simplified
}

#endif // FEAT_061_MQH
