// feat_008.mqh  — sma_20
// Auto-generated by gen_feat_mqh.py  (feature index 8)
// Python: features.py BASE_FEATURE_COLS[8] = "sma_20"
#ifndef FEAT_008_MQH
#define FEAT_008_MQH



double CalcFeat_008(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double sum = 0.0;
   int cnt = 0;
   for(int k = i; k < i + 20 && k < needed; k++) { sum += close[k]; cnt++; }
   return (cnt > 0) ? sum / cnt : close[i];
}

#endif // FEAT_008_MQH
