// feat_178.mqh  — price_diff_30
// Auto-generated by gen_feat_mqh.py  (feature index 178)
// Python: features.py BASE_FEATURE_COLS[178] = "price_diff_30"
#ifndef FEAT_178_MQH
#define FEAT_178_MQH



double CalcFeat_178(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+30<needed)?close[i]-close[i+30]:0.0;
}

#endif // FEAT_178_MQH
