// feat_126.mqh  — dow_cos
// Auto-generated by gen_feat_mqh.py  (feature index 126)
// Python: features.py BASE_FEATURE_COLS[126] = "dow_cos"
#ifndef FEAT_126_MQH
#define FEAT_126_MQH

// Requires GetBarTime(int i) defined in main EA

double CalcFeat_126(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   MqlDateTime mdt; TimeToStruct(GetBarTime(i),mdt);
   int hr=mdt.hour;
   int dow=mdt.day_of_week;
   
   
   
   return MathCos(2.0*M_PI*dow/5.0);
   
   
   
   
}

#endif // FEAT_126_MQH
