// feat_142.mqh  — vol_20
// Auto-generated by gen_feat_mqh.py  (feature index 142)
// Python: features.py BASE_FEATURE_COLS[142] = "vol_20"
#ifndef FEAT_142_MQH
#define FEAT_142_MQH



double CalcFeat_142(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<20&&i+k<needed;k++){s+=vol[i+k];c2++;}
   return (c2>0)?s/c2:0;
}

#endif // FEAT_142_MQH
