// feat_161.mqh  — momentum_5
// Auto-generated by gen_feat_mqh.py  (feature index 161)
// Python: features.py BASE_FEATURE_COLS[161] = "momentum_5"
#ifndef FEAT_161_MQH
#define FEAT_161_MQH



double CalcFeat_161(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+5<needed)?close[i]-close[i+5]:0.0;
}

#endif // FEAT_161_MQH
