// feat_078.mqh  — ichi_kijun
// Auto-generated by gen_feat_mqh.py  (feature index 78)
// Python: features.py BASE_FEATURE_COLS[78] = "ichi_kijun"
#ifndef FEAT_078_MQH
#define FEAT_078_MQH



double CalcFeat_078(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double hi=high[i],lo=low[i];
   for(int k=1;k<26&&i+k<needed;k++){hi=MathMax(hi,high[i+k]);lo=MathMin(lo,low[i+k]);}
   return (hi+lo)/2.0;
}

#endif // FEAT_078_MQH
