// feat_094.mqh  — roll_mean_30
// Auto-generated by gen_feat_mqh.py  (feature index 94)
// Python: features.py BASE_FEATURE_COLS[94] = "roll_mean_30"
#ifndef FEAT_094_MQH
#define FEAT_094_MQH



double CalcFeat_094(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<30&&i+k<needed;k++){s+=close[i+k];c2++;}
   return (c2>0)?s/c2:close[i];
}

#endif // FEAT_094_MQH
