// feat_101.mqh  — lower_w
// Auto-generated by gen_feat_mqh.py  (feature index 101)
// Python: features.py BASE_FEATURE_COLS[101] = "lower_w"
#ifndef FEAT_101_MQH
#define FEAT_101_MQH



double CalcFeat_101(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{
   return MathMin(close[i],open[i])-low[i];
}

#endif // FEAT_101_MQH
