// feat_130.mqh  — is_overlap
// Auto-generated by gen_feat_mqh.py  (feature index 130)
// Python: features.py BASE_FEATURE_COLS[130] = "is_overlap"
#ifndef FEAT_130_MQH
#define FEAT_130_MQH

// Requires GetBarTime(int i) defined in main EA

double CalcFeat_130(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   MqlDateTime mdt; TimeToStruct(GetBarTime(i),mdt);
   int hr=mdt.hour;
   
   
   
   
   
   
   
   
   return (hr>=13&&hr<16)?1.0:0.0;
}

#endif // FEAT_130_MQH
