// feat_143.mqh  — ret1_25
// Auto-generated by gen_feat_mqh.py  (feature index 143)
// Python: features.py BASE_FEATURE_COLS[143] = "ret1_25"
#ifndef FEAT_143_MQH
#define FEAT_143_MQH



double CalcFeat_143(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+25<needed)?close[i+25]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_143_MQH
