// feat_055.mqh  — atr_28
// Auto-generated by gen_feat_mqh.py  (feature index 55)
// Python: features.py BASE_FEATURE_COLS[55] = "atr_28"
#ifndef FEAT_055_MQH
#define FEAT_055_MQH



double CalcFeat_055(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double alpha=1.0/28.0;
   double tr0=high[needed-1]-low[needed-1], rm=tr0;
   for(int k=needed-2;k>=i;k--){
      double hl=high[k]-low[k];
      double hpc=MathAbs(high[k]-close[k+1]);
      double lpc=MathAbs(low[k]-close[k+1]);
      double tr=MathMax(hl,MathMax(hpc,lpc));
      rm=alpha*tr+(1-alpha)*rm;
   }
   return rm;
}

#endif // FEAT_055_MQH
