// feat_150.mqh  — ret5_35
// Auto-generated by gen_feat_mqh.py  (feature index 150)
// Python: features.py BASE_FEATURE_COLS[150] = "ret5_35"
#ifndef FEAT_150_MQH
#define FEAT_150_MQH



double CalcFeat_150(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+5<needed)?close[i+5]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_150_MQH
