// feat_009.mqh  — ema_20
// Auto-generated by gen_feat_mqh.py  (feature index 9)
// Python: features.py BASE_FEATURE_COLS[9] = "ema_20"
#ifndef FEAT_009_MQH
#define FEAT_009_MQH



double CalcFeat_009(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double alpha = 2.0 / (20.0 + 1.0);
   double em = close[needed-1];
   for(int k = needed-2; k >= i; k--)
      em = alpha * close[k] + (1.0 - alpha) * em;
   return em;
}

#endif // FEAT_009_MQH
