// feat_084.mqh  — roll_mean_10
// Auto-generated by gen_feat_mqh.py  (feature index 84)
// Python: features.py BASE_FEATURE_COLS[84] = "roll_mean_10"
#ifndef FEAT_084_MQH
#define FEAT_084_MQH



double CalcFeat_084(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<10&&i+k<needed;k++){s+=close[i+k];c2++;}
   return (c2>0)?s/c2:close[i];
}

#endif // FEAT_084_MQH
