// feat_088.mqh  — zscore_10
// Auto-generated by gen_feat_mqh.py  (feature index 88)
// Python: features.py BASE_FEATURE_COLS[88] = "zscore_10"
#ifndef FEAT_088_MQH
#define FEAT_088_MQH



double CalcFeat_088(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<10&&i+k<needed;k++){s+=close[i+k];c2++;}
   double m=(c2>0)?s/c2:close[i];
   double sq=0;
   for(int k=0;k<10&&i+k<needed;k++){double d=close[i+k]-m;sq+=d*d;}
   double std=MathSqrt((c2>0)?sq/c2:0);
   return (std>1e-12)?(close[i]-m)/std:0.0;
}

#endif // FEAT_088_MQH
