// feat_229.mqh  — price_diff_115
// Auto-generated by gen_feat_mqh.py  (feature index 229)
// Python: features.py BASE_FEATURE_COLS[229] = "price_diff_115"
#ifndef FEAT_229_MQH
#define FEAT_229_MQH



double CalcFeat_229(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+115<needed)?close[i]-close[i+115]:0.0;
}

#endif // FEAT_229_MQH
