// feat_017.mqh  — ema_100
// Auto-generated by gen_feat_mqh.py  (feature index 17)
// Python: features.py BASE_FEATURE_COLS[17] = "ema_100"
#ifndef FEAT_017_MQH
#define FEAT_017_MQH



double CalcFeat_017(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double alpha = 2.0 / (100.0 + 1.0);
   double em = close[needed-1];
   for(int k = needed-2; k >= i; k--)
      em = alpha * close[k] + (1.0 - alpha) * em;
   return em;
}

#endif // FEAT_017_MQH
