// feat_140.mqh  — ret1_20
// Auto-generated by gen_feat_mqh.py  (feature index 140)
// Python: features.py BASE_FEATURE_COLS[140] = "ret1_20"
#ifndef FEAT_140_MQH
#define FEAT_140_MQH



double CalcFeat_140(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+20<needed)?close[i+20]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_140_MQH
