// feat_179.mqh  — momentum_35
// Auto-generated by gen_feat_mqh.py  (feature index 179)
// Python: features.py BASE_FEATURE_COLS[179] = "momentum_35"
#ifndef FEAT_179_MQH
#define FEAT_179_MQH



double CalcFeat_179(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+35<needed)?close[i]-close[i+35]:0.0;
}

#endif // FEAT_179_MQH
