// feat_166.mqh  — price_diff_10
// Auto-generated by gen_feat_mqh.py  (feature index 166)
// Python: features.py BASE_FEATURE_COLS[166] = "price_diff_10"
#ifndef FEAT_166_MQH
#define FEAT_166_MQH



double CalcFeat_166(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+10<needed)?close[i]-close[i+10]:0.0;
}

#endif // FEAT_166_MQH
