// feat_069.mqh  — kc_pos_20
// Auto-generated by gen_feat_mqh.py  (feature index 69)
// Python: features.py BASE_FEATURE_COLS[69] = "kc_pos_20"
#ifndef FEAT_069_MQH
#define FEAT_069_MQH



double CalcFeat_069(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   // KC pos (ema20 ± 1.5*atr14)
   double alpha_ema=2.0/21.0, alpha_rma=1.0/14.0;
   double em=close[needed-1];
   double rm=high[needed-1]-low[needed-1];
   for(int k=needed-2;k>=i;k--){
      em=alpha_ema*close[k]+(1-alpha_ema)*em;
      double hl=high[k]-low[k],hpc=MathAbs(high[k]-close[k+1]),lpc=MathAbs(low[k]-close[k+1]);
      rm=alpha_rma*MathMax(hl,MathMax(hpc,lpc))+(1-alpha_rma)*rm;
   }
   double kc_u=em+1.5*rm, kc_d=em-1.5*rm;
   return (close[i]-kc_d)/(kc_u-kc_d+1e-9);
}

#endif // FEAT_069_MQH
