// feat_197.mqh  — momentum_65
// Auto-generated by gen_feat_mqh.py  (feature index 197)
// Python: features.py BASE_FEATURE_COLS[197] = "momentum_65"
#ifndef FEAT_197_MQH
#define FEAT_197_MQH



double CalcFeat_197(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+65<needed)?close[i]-close[i+65]:0.0;
}

#endif // FEAT_197_MQH
