// feat_193.mqh  — price_diff_55
// Auto-generated by gen_feat_mqh.py  (feature index 193)
// Python: features.py BASE_FEATURE_COLS[193] = "price_diff_55"
#ifndef FEAT_193_MQH
#define FEAT_193_MQH



double CalcFeat_193(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+55<needed)?close[i]-close[i+55]:0.0;
}

#endif // FEAT_193_MQH
