// feat_173.mqh  — momentum_25
// Auto-generated by gen_feat_mqh.py  (feature index 173)
// Python: features.py BASE_FEATURE_COLS[173] = "momentum_25"
#ifndef FEAT_173_MQH
#define FEAT_173_MQH



double CalcFeat_173(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+25<needed)?close[i]-close[i+25]:0.0;
}

#endif // FEAT_173_MQH
