// feat_104.mqh  — is_bull_engulf
// Auto-generated by gen_feat_mqh.py  (feature index 104)
// Python: features.py BASE_FEATURE_COLS[104] = "is_bull_engulf"
#ifndef FEAT_104_MQH
#define FEAT_104_MQH



double CalcFeat_104(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   if(!(i+1<needed)) return 0.0;
   double body_cur=close[i]-open[i];
   double body_prv=close[i+1]-open[i+1];
   return (body_cur>0&&body_prv<0&&open[i]<=close[i+1]&&close[i]>=open[i+1])?1.0:0.0;
}

#endif // FEAT_104_MQH
