// feat_002.mqh  — hma_5
// Auto-generated by gen_feat_mqh.py  (feature index 2)
// Python: features.py BASE_FEATURE_COLS[2] = "hma_5"
#ifndef FEAT_002_MQH
#define FEAT_002_MQH



double CalcFeat_002(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   // HMA(5) = WMA(2*WMA(2)-WMA(5), sqrt(5))
   double num_h=0,den_h=0, num_f=0,den_f=0;
   for(int k=0;k<2&&i+k<needed;k++){double w=2-k; num_h+=close[i+k]*w; den_h+=w;}
   for(int k=0;k<5&&i+k<needed;k++){double w=5-k; num_f+=close[i+k]*w; den_f+=w;}
   double wma_half=(den_h>0)?num_h/den_h:close[i];
   double wma_full=(den_f>0)?num_f/den_f:close[i];
   double diff_val = 2.0*wma_half - wma_full;
   // WMA(diff, 2): need series of diff at i+0..i+1
   double num_s=0,den_s=0;
   for(int k=0;k<2&&i+k<needed;k++){
      double nh=0,dh=0,nf=0,df=0;
      for(int j=0;j<2&&i+k+j<needed;j++){double w=2-j;nh+=close[i+k+j]*w;dh+=w;}
      for(int j=0;j<5&&i+k+j<needed;j++){double w=5-j;nf+=close[i+k+j]*w;df+=w;}
      double dv=2.0*(dh>0?nh/dh:close[i+k])-(df>0?nf/df:close[i+k]);
      double w=2-k; num_s+=dv*w; den_s+=w;
   }
   return (den_s>0)?num_s/den_s:diff_val;
}

#endif // FEAT_002_MQH
