// feat_049.mqh  — atr_14
// Auto-generated by gen_feat_mqh.py  (feature index 49)
// Python: features.py BASE_FEATURE_COLS[49] = "atr_14"
#ifndef FEAT_049_MQH
#define FEAT_049_MQH



double CalcFeat_049(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double alpha=1.0/14.0;
   double tr0=high[needed-1]-low[needed-1], rm=tr0;
   for(int k=needed-2;k>=i;k--){
      double hl=high[k]-low[k];
      double hpc=MathAbs(high[k]-close[k+1]);
      double lpc=MathAbs(low[k]-close[k+1]);
      double tr=MathMax(hl,MathMax(hpc,lpc));
      rm=alpha*tr+(1-alpha)*rm;
   }
   return rm;
}

#endif // FEAT_049_MQH
