// feat_087.mqh  — roll_kurt_10
// Auto-generated by gen_feat_mqh.py  (feature index 87)
// Python: features.py BASE_FEATURE_COLS[87] = "roll_kurt_10"
#ifndef FEAT_087_MQH
#define FEAT_087_MQH



double CalcFeat_087(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<10&&i+k<needed;k++){s+=close[i+k];c2++;}
   double m=(c2>0)?s/c2:close[i];
   double sq=0;
   for(int k=0;k<10&&i+k<needed;k++){double d=close[i+k]-m;sq+=d*d;}
   double std=MathSqrt((c2>0)?sq/c2:0);
   if(std<1e-12) return 0.0;
   double kurt=0;
   for(int k=0;k<10&&i+k<needed;k++){double d=(close[i+k]-m)/std;kurt+=d*d*d*d;}
   return (c2>0)?kurt/c2-3.0:0;
}

#endif // FEAT_087_MQH
