// feat_198.mqh  — volatility_65
// Auto-generated by gen_feat_mqh.py  (feature index 198)
// Python: features.py BASE_FEATURE_COLS[198] = "volatility_65"
#ifndef FEAT_198_MQH
#define FEAT_198_MQH



double CalcFeat_198(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0;int c2=0;
   for(int k=0;k<65&&i+k<needed;k++){s+=close[i+k];c2++;}
   double m=(c2>0)?s/c2:close[i];
   double sq=0;
   for(int k=0;k<65&&i+k<needed;k++){double d=close[i+k]-m;sq+=d*d;}
   return MathSqrt((c2>0)?sq/c2:0);
}

#endif // FEAT_198_MQH
