// feat_128.mqh  — is_london
// Auto-generated by gen_feat_mqh.py  (feature index 128)
// Python: features.py BASE_FEATURE_COLS[128] = "is_london"
#ifndef FEAT_128_MQH
#define FEAT_128_MQH

// Requires GetBarTime(int i) defined in main EA

double CalcFeat_128(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   MqlDateTime mdt; TimeToStruct(GetBarTime(i),mdt);
   int hr=mdt.hour;
   
   
   
   
   
   
   return (hr>=7&&hr<16)?1.0:0.0;
   
   
}

#endif // FEAT_128_MQH
