// feat_108.mqh  — hh
// Auto-generated by gen_feat_mqh.py  (feature index 108)
// Python: features.py BASE_FEATURE_COLS[108] = "hh"
#ifndef FEAT_108_MQH
#define FEAT_108_MQH



double CalcFeat_108(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{
   return (i+1<needed&&high[i]>high[i+1])?1.0:0.0;
}

#endif // FEAT_108_MQH
