// feat_141.mqh  — ret5_20
// Auto-generated by gen_feat_mqh.py  (feature index 141)
// Python: features.py BASE_FEATURE_COLS[141] = "ret5_20"
#ifndef FEAT_141_MQH
#define FEAT_141_MQH



double CalcFeat_141(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+5<needed)?close[i+5]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_141_MQH
