// feat_075.mqh  — diff_sma_200
// Auto-generated by gen_feat_mqh.py  (feature index 75)
// Python: features.py BASE_FEATURE_COLS[75] = "diff_sma_200"
#ifndef FEAT_075_MQH
#define FEAT_075_MQH



double CalcFeat_075(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<200&&i+k<needed;k++){s+=close[i+k];c2++;}
   double m=(c2>0)?s/c2:close[i];
   return (close[i]-m)/(close[i]+1e-9);
}

#endif // FEAT_075_MQH
