// feat_195.mqh  — volatility_60
// Auto-generated by gen_feat_mqh.py  (feature index 195)
// Python: features.py BASE_FEATURE_COLS[195] = "volatility_60"
#ifndef FEAT_195_MQH
#define FEAT_195_MQH



double CalcFeat_195(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0;int c2=0;
   for(int k=0;k<60&&i+k<needed;k++){s+=close[i+k];c2++;}
   double m=(c2>0)?s/c2:close[i];
   double sq=0;
   for(int k=0;k<60&&i+k<needed;k++){double d=close[i+k]-m;sq+=d*d;}
   return MathSqrt((c2>0)?sq/c2:0);
}

#endif // FEAT_195_MQH
