// feat_018.mqh  — sma_200
// Auto-generated by gen_feat_mqh.py  (feature index 18)
// Python: features.py BASE_FEATURE_COLS[18] = "sma_200"
#ifndef FEAT_018_MQH
#define FEAT_018_MQH



double CalcFeat_018(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double sum = 0.0;
   int cnt = 0;
   for(int k = i; k < i + 200 && k < needed; k++) { sum += close[k]; cnt++; }
   return (cnt > 0) ? sum / cnt : close[i];
}

#endif // FEAT_018_MQH
