// feat_107.mqh  — is_inv_hammer
// Auto-generated by gen_feat_mqh.py  (feature index 107)
// Python: features.py BASE_FEATURE_COLS[107] = "is_inv_hammer"
#ifndef FEAT_107_MQH
#define FEAT_107_MQH



double CalcFeat_107(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double body=MathAbs(close[i]-open[i]);
   double lower=MathMin(close[i],open[i])-low[i];
   double upper=high[i]-MathMax(close[i],open[i]);
   return (upper>body*2&&lower<body*0.5)?1.0:0.0;
}

#endif // FEAT_107_MQH
