// feat_019.mqh  — ema_200
// Auto-generated by gen_feat_mqh.py  (feature index 19)
// Python: features.py BASE_FEATURE_COLS[19] = "ema_200"
#ifndef FEAT_019_MQH
#define FEAT_019_MQH



double CalcFeat_019(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double alpha = 2.0 / (200.0 + 1.0);
   double em = close[needed-1];
   for(int k = needed-2; k >= i; k--)
      em = alpha * close[k] + (1.0 - alpha) * em;
   return em;
}

#endif // FEAT_019_MQH
