// feat_184.mqh  — price_diff_40
// Auto-generated by gen_feat_mqh.py  (feature index 184)
// Python: features.py BASE_FEATURE_COLS[184] = "price_diff_40"
#ifndef FEAT_184_MQH
#define FEAT_184_MQH



double CalcFeat_184(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+40<needed)?close[i]-close[i+40]:0.0;
}

#endif // FEAT_184_MQH
