// feat_214.mqh  — price_diff_90
// Auto-generated by gen_feat_mqh.py  (feature index 214)
// Python: features.py BASE_FEATURE_COLS[214] = "price_diff_90"
#ifndef FEAT_214_MQH
#define FEAT_214_MQH



double CalcFeat_214(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+90<needed)?close[i]-close[i+90]:0.0;
}

#endif // FEAT_214_MQH
