// feat_013.mqh  — ema_50
// Auto-generated by gen_feat_mqh.py  (feature index 13)
// Python: features.py BASE_FEATURE_COLS[13] = "ema_50"
#ifndef FEAT_013_MQH
#define FEAT_013_MQH



double CalcFeat_013(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double alpha = 2.0 / (50.0 + 1.0);
   double em = close[needed-1];
   for(int k = needed-2; k >= i; k--)
      em = alpha * close[k] + (1.0 - alpha) * em;
   return em;
}

#endif // FEAT_013_MQH
