// feat_209.mqh  — momentum_85
// Auto-generated by gen_feat_mqh.py  (feature index 209)
// Python: features.py BASE_FEATURE_COLS[209] = "momentum_85"
#ifndef FEAT_209_MQH
#define FEAT_209_MQH



double CalcFeat_209(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+85<needed)?close[i]-close[i+85]:0.0;
}

#endif // FEAT_209_MQH
