// feat_200.mqh  — momentum_70
// Auto-generated by gen_feat_mqh.py  (feature index 200)
// Python: features.py BASE_FEATURE_COLS[200] = "momentum_70"
#ifndef FEAT_200_MQH
#define FEAT_200_MQH



double CalcFeat_200(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+70<needed)?close[i]-close[i+70]:0.0;
}

#endif // FEAT_200_MQH
