// feat_072.mqh  — diff_ema_20
// Auto-generated by gen_feat_mqh.py  (feature index 72)
// Python: features.py BASE_FEATURE_COLS[72] = "diff_ema_20"
#ifndef FEAT_072_MQH
#define FEAT_072_MQH



double CalcFeat_072(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double alpha=2.0/(20.0+1.0);
   double em=close[needed-1];
   for(int k=needed-2;k>=i;k--) em=alpha*close[k]+(1-alpha)*em;
   return (close[i]-em)/(close[i]+1e-9);
}

#endif // FEAT_072_MQH
