// feat_217.mqh  — price_diff_95
// Auto-generated by gen_feat_mqh.py  (feature index 217)
// Python: features.py BASE_FEATURE_COLS[217] = "price_diff_95"
#ifndef FEAT_217_MQH
#define FEAT_217_MQH



double CalcFeat_217(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+95<needed)?close[i]-close[i+95]:0.0;
}

#endif // FEAT_217_MQH
