// feat_132.mqh  — ret5_5
// Auto-generated by gen_feat_mqh.py  (feature index 132)
// Python: features.py BASE_FEATURE_COLS[132] = "ret5_5"
#ifndef FEAT_132_MQH
#define FEAT_132_MQH



double CalcFeat_132(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+5<needed)?close[i+5]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_132_MQH
