// feat_221.mqh  — momentum_105
// Auto-generated by gen_feat_mqh.py  (feature index 221)
// Python: features.py BASE_FEATURE_COLS[221] = "momentum_105"
#ifndef FEAT_221_MQH
#define FEAT_221_MQH



double CalcFeat_221(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+105<needed)?close[i]-close[i+105]:0.0;
}

#endif // FEAT_221_MQH
