// feat_112.mqh  — bos
// Auto-generated by gen_feat_mqh.py  (feature index 112)
// Python: features.py BASE_FEATURE_COLS[112] = "bos"
#ifndef FEAT_112_MQH
#define FEAT_112_MQH



double CalcFeat_112(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   if(i+1>=needed) return 0.0;
   bool hl=(low[i]>low[i+1]), hh=(high[i]>high[i+1]);
   bool lh=(high[i]<high[i+1]), ll=(low[i]<low[i+1]);
   bool bull_bos=(i+2<needed&&low[i+1]>low[i+2]&&hh);
   bool bear_bos=(i+2<needed&&high[i+1]<high[i+2]&&ll);
   return (bull_bos||bear_bos)?1.0:0.0;
}

#endif // FEAT_112_MQH
