// feat_181.mqh  — price_diff_35
// Auto-generated by gen_feat_mqh.py  (feature index 181)
// Python: features.py BASE_FEATURE_COLS[181] = "price_diff_35"
#ifndef FEAT_181_MQH
#define FEAT_181_MQH



double CalcFeat_181(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+35<needed)?close[i]-close[i+35]:0.0;
}

#endif // FEAT_181_MQH
