// feat_176.mqh  — momentum_30
// Auto-generated by gen_feat_mqh.py  (feature index 176)
// Python: features.py BASE_FEATURE_COLS[176] = "momentum_30"
#ifndef FEAT_176_MQH
#define FEAT_176_MQH



double CalcFeat_176(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+30<needed)?close[i]-close[i+30]:0.0;
}

#endif // FEAT_176_MQH
