// feat_109.mqh  — hl
// Auto-generated by gen_feat_mqh.py  (feature index 109)
// Python: features.py BASE_FEATURE_COLS[109] = "hl"
#ifndef FEAT_109_MQH
#define FEAT_109_MQH



double CalcFeat_109(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{
   return (i+1<needed&&low[i]>low[i+1])?1.0:0.0;
}

#endif // FEAT_109_MQH
