// feat_043.mqh  — atr_7
// Auto-generated by gen_feat_mqh.py  (feature index 43)
// Python: features.py BASE_FEATURE_COLS[43] = "atr_7"
#ifndef FEAT_043_MQH
#define FEAT_043_MQH



double CalcFeat_043(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double alpha=1.0/7.0;
   double tr0=high[needed-1]-low[needed-1], rm=tr0;
   for(int k=needed-2;k>=i;k--){
      double hl=high[k]-low[k];
      double hpc=MathAbs(high[k]-close[k+1]);
      double lpc=MathAbs(low[k]-close[k+1]);
      double tr=MathMax(hl,MathMax(hpc,lpc));
      rm=alpha*tr+(1-alpha)*rm;
   }
   return rm;
}

#endif // FEAT_043_MQH
