// feat_139.mqh  — vol_15
// Auto-generated by gen_feat_mqh.py  (feature index 139)
// Python: features.py BASE_FEATURE_COLS[139] = "vol_15"
#ifndef FEAT_139_MQH
#define FEAT_139_MQH



double CalcFeat_139(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<15&&i+k<needed;k++){s+=vol[i+k];c2++;}
   return (c2>0)?s/c2:0;
}

#endif // FEAT_139_MQH
