// feat_145.mqh  — vol_25
// Auto-generated by gen_feat_mqh.py  (feature index 145)
// Python: features.py BASE_FEATURE_COLS[145] = "vol_25"
#ifndef FEAT_145_MQH
#define FEAT_145_MQH



double CalcFeat_145(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<25&&i+k<needed;k++){s+=vol[i+k];c2++;}
   return (c2>0)?s/c2:0;
}

#endif // FEAT_145_MQH
