// feat_167.mqh  — momentum_15
// Auto-generated by gen_feat_mqh.py  (feature index 167)
// Python: features.py BASE_FEATURE_COLS[167] = "momentum_15"
#ifndef FEAT_167_MQH
#define FEAT_167_MQH



double CalcFeat_167(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+15<needed)?close[i]-close[i+15]:0.0;
}

#endif // FEAT_167_MQH
