// feat_224.mqh  — momentum_110
// Auto-generated by gen_feat_mqh.py  (feature index 224)
// Python: features.py BASE_FEATURE_COLS[224] = "momentum_110"
#ifndef FEAT_224_MQH
#define FEAT_224_MQH



double CalcFeat_224(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+110<needed)?close[i]-close[i+110]:0.0;
}

#endif // FEAT_224_MQH
