// feat_081.mqh  — ichi_cloud_pos
// Auto-generated by gen_feat_mqh.py  (feature index 81)
// Python: features.py BASE_FEATURE_COLS[81] = "ichi_cloud_pos"
#ifndef FEAT_081_MQH
#define FEAT_081_MQH



double CalcFeat_081(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double hi9=high[i],lo9=low[i]; for(int k=1;k<9&&i+k<needed;k++){hi9=MathMax(hi9,high[i+k]);lo9=MathMin(lo9,low[i+k]);}
   double tk=(hi9+lo9)/2.0;
   double hi26=high[i],lo26=low[i]; for(int k=1;k<26&&i+k<needed;k++){hi26=MathMax(hi26,high[i+k]);lo26=MathMin(lo26,low[i+k]);}
   double kj=(hi26+lo26)/2.0;
   double sa=(tk+kj)/2.0;
   double hi52=high[i],lo52=low[i]; for(int k=1;k<52&&i+k<needed;k++){hi52=MathMax(hi52,high[i+k]);lo52=MathMin(lo52,low[i+k]);}
   double sb=(hi52+lo52)/2.0;
   double top=MathMax(sa,sb), bot=MathMin(sa,sb);
   return (close[i]-bot)/(top-bot+1e-9);
}

#endif // FEAT_081_MQH
