// feat_120.mqh  — bos_ema_sync
// Auto-generated by gen_feat_mqh.py  (feature index 120)
// Python: features.py BASE_FEATURE_COLS[120] = "bos_ema_sync"
#ifndef FEAT_120_MQH
#define FEAT_120_MQH



double CalcFeat_120(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{
   return 0.0;
}

#endif // FEAT_120_MQH
