// feat_156.mqh  — ret5_45
// Auto-generated by gen_feat_mqh.py  (feature index 156)
// Python: features.py BASE_FEATURE_COLS[156] = "ret5_45"
#ifndef FEAT_156_MQH
#define FEAT_156_MQH



double CalcFeat_156(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+5<needed)?close[i+5]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_156_MQH
