// feat_073.mqh  — diff_sma_50
// Auto-generated by gen_feat_mqh.py  (feature index 73)
// Python: features.py BASE_FEATURE_COLS[73] = "diff_sma_50"
#ifndef FEAT_073_MQH
#define FEAT_073_MQH



double CalcFeat_073(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<50&&i+k<needed;k++){s+=close[i+k];c2++;}
   double m=(c2>0)?s/c2:close[i];
   return (close[i]-m)/(close[i]+1e-9);
}

#endif // FEAT_073_MQH
