// feat_005.mqh  — ema_10
// Auto-generated by gen_feat_mqh.py  (feature index 5)
// Python: features.py BASE_FEATURE_COLS[5] = "ema_10"
#ifndef FEAT_005_MQH
#define FEAT_005_MQH



double CalcFeat_005(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double alpha = 2.0 / (10.0 + 1.0);
   double em = close[needed-1];
   for(int k = needed-2; k >= i; k--)
      em = alpha * close[k] + (1.0 - alpha) * em;
   return em;
}

#endif // FEAT_005_MQH
