// feat_113.mqh  — bos_dir
// Auto-generated by gen_feat_mqh.py  (feature index 113)
// Python: features.py BASE_FEATURE_COLS[113] = "bos_dir"
#ifndef FEAT_113_MQH
#define FEAT_113_MQH



double CalcFeat_113(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   if(i+1>=needed) return 0.0;
   bool hh=(high[i]>high[i+1]), ll=(low[i]<low[i+1]);
   bool bull_bos=(i+2<needed&&low[i+1]>low[i+2]&&hh);
   bool bear_bos=(i+2<needed&&high[i+1]<high[i+2]&&ll);
   return bull_bos?1.0:(bear_bos?-1.0:0.0);
}

#endif // FEAT_113_MQH
