// feat_223.mqh  — price_diff_105
// Auto-generated by gen_feat_mqh.py  (feature index 223)
// Python: features.py BASE_FEATURE_COLS[223] = "price_diff_105"
#ifndef FEAT_223_MQH
#define FEAT_223_MQH



double CalcFeat_223(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+105<needed)?close[i]-close[i+105]:0.0;
}

#endif // FEAT_223_MQH
