// feat_226.mqh  — price_diff_110
// Auto-generated by gen_feat_mqh.py  (feature index 226)
// Python: features.py BASE_FEATURE_COLS[226] = "price_diff_110"
#ifndef FEAT_226_MQH
#define FEAT_226_MQH



double CalcFeat_226(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+110<needed)?close[i]-close[i+110]:0.0;
}

#endif // FEAT_226_MQH
