// feat_028.mqh  — macdhist_5_34_5
// Auto-generated by gen_feat_mqh.py  (feature index 28)
// Python: features.py BASE_FEATURE_COLS[28] = "macdhist_5_34_5"
#ifndef FEAT_028_MQH
#define FEAT_028_MQH



double CalcFeat_028(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   // MACD(5,34,5) hist
   double af=0.3333333333333333, as_=0.05714285714285714, asig=0.3333333333333333;
   double ef=close[needed-1], es=close[needed-1];
   for(int k=needed-2;k>=i;k--){ef=af*close[k]+(1-af)*ef; es=as_*close[k]+(1-as_)*es;}
   double ml=ef-es;
   // sig: need series of macd_line values back sig bars
   double sig_val=ml;
   // approx: run EMA of macd_line over full series
   double ef2=close[needed-1], es2=close[needed-1], prev_ml=0, sv=0;
   int first=1;
   for(int k=needed-2;k>=i;k--){
      ef2=af*close[k]+(1-af)*ef2; es2=as_*close[k]+(1-as_)*es2;
      double cur_ml=ef2-es2;
      if(first){sv=cur_ml;first=0;} else sv=asig*cur_ml+(1-asig)*sv;
   }
   sig_val=sv;
   return ml - sig_val;
}

#endif // FEAT_028_MQH
