// feat_159.mqh  — ret5_50
// Auto-generated by gen_feat_mqh.py  (feature index 159)
// Python: features.py BASE_FEATURE_COLS[159] = "ret5_50"
#ifndef FEAT_159_MQH
#define FEAT_159_MQH



double CalcFeat_159(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+5<needed)?close[i+5]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_159_MQH
