// feat_187.mqh  — price_diff_45
// Auto-generated by gen_feat_mqh.py  (feature index 187)
// Python: features.py BASE_FEATURE_COLS[187] = "price_diff_45"
#ifndef FEAT_187_MQH
#define FEAT_187_MQH



double CalcFeat_187(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+45<needed)?close[i]-close[i+45]:0.0;
}

#endif // FEAT_187_MQH
