// feat_215.mqh  — momentum_95
// Auto-generated by gen_feat_mqh.py  (feature index 215)
// Python: features.py BASE_FEATURE_COLS[215] = "momentum_95"
#ifndef FEAT_215_MQH
#define FEAT_215_MQH



double CalcFeat_215(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+95<needed)?close[i]-close[i+95]:0.0;
}

#endif // FEAT_215_MQH
