// feat_071.mqh  — diff_sma_20
// Auto-generated by gen_feat_mqh.py  (feature index 71)
// Python: features.py BASE_FEATURE_COLS[71] = "diff_sma_20"
#ifndef FEAT_071_MQH
#define FEAT_071_MQH



double CalcFeat_071(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<20&&i+k<needed;k++){s+=close[i+k];c2++;}
   double m=(c2>0)?s/c2:close[i];
   return (close[i]-m)/(close[i]+1e-9);
}

#endif // FEAT_071_MQH
