// feat_194.mqh  — momentum_60
// Auto-generated by gen_feat_mqh.py  (feature index 194)
// Python: features.py BASE_FEATURE_COLS[194] = "momentum_60"
#ifndef FEAT_194_MQH
#define FEAT_194_MQH



double CalcFeat_194(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+60<needed)?close[i]-close[i+60]:0.0;
}

#endif // FEAT_194_MQH
