// feat_091.mqh  — roll_skew_20
// Auto-generated by gen_feat_mqh.py  (feature index 91)
// Python: features.py BASE_FEATURE_COLS[91] = "roll_skew_20"
#ifndef FEAT_091_MQH
#define FEAT_091_MQH



double CalcFeat_091(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<20&&i+k<needed;k++){s+=close[i+k];c2++;}
   double m=(c2>0)?s/c2:close[i];
   double sq=0;
   for(int k=0;k<20&&i+k<needed;k++){double d=close[i+k]-m;sq+=d*d;}
   double std=MathSqrt((c2>0)?sq/c2:0);
   if(std<1e-12) return 0.0;
   double skew=0;
   for(int k=0;k<20&&i+k<needed;k++){double d=(close[i+k]-m)/std;skew+=d*d*d;}
   return (c2>0)?skew/c2:0;
}

#endif // FEAT_091_MQH
