// feat_074.mqh  — diff_ema_50
// Auto-generated by gen_feat_mqh.py  (feature index 74)
// Python: features.py BASE_FEATURE_COLS[74] = "diff_ema_50"
#ifndef FEAT_074_MQH
#define FEAT_074_MQH



double CalcFeat_074(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double alpha=2.0/(50.0+1.0);
   double em=close[needed-1];
   for(int k=needed-2;k>=i;k--) em=alpha*close[k]+(1-alpha)*em;
   return (close[i]-em)/(close[i]+1e-9);
}

#endif // FEAT_074_MQH
