// feat_103.mqh  — is_doji
// Auto-generated by gen_feat_mqh.py  (feature index 103)
// Python: features.py BASE_FEATURE_COLS[103] = "is_doji"
#ifndef FEAT_103_MQH
#define FEAT_103_MQH



double CalcFeat_103(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double hl=high[i]-low[i]+1e-9;
   return (MathAbs(close[i]-open[i])<hl*0.1)?1.0:0.0;
}

#endif // FEAT_103_MQH
