// feat_190.mqh  — price_diff_50
// Auto-generated by gen_feat_mqh.py  (feature index 190)
// Python: features.py BASE_FEATURE_COLS[190] = "price_diff_50"
#ifndef FEAT_190_MQH
#define FEAT_190_MQH



double CalcFeat_190(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+50<needed)?close[i]-close[i+50]:0.0;
}

#endif // FEAT_190_MQH
