// feat_134.mqh  — ret1_10
// Auto-generated by gen_feat_mqh.py  (feature index 134)
// Python: features.py BASE_FEATURE_COLS[134] = "ret1_10"
#ifndef FEAT_134_MQH
#define FEAT_134_MQH



double CalcFeat_134(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+10<needed)?close[i+10]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_134_MQH
