// feat_147.mqh  — ret5_30
// Auto-generated by gen_feat_mqh.py  (feature index 147)
// Python: features.py BASE_FEATURE_COLS[147] = "ret5_30"
#ifndef FEAT_147_MQH
#define FEAT_147_MQH



double CalcFeat_147(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+5<needed)?close[i+5]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_147_MQH
