// feat_164.mqh  — momentum_10
// Auto-generated by gen_feat_mqh.py  (feature index 164)
// Python: features.py BASE_FEATURE_COLS[164] = "momentum_10"
#ifndef FEAT_164_MQH
#define FEAT_164_MQH



double CalcFeat_164(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+10<needed)?close[i]-close[i+10]:0.0;
}

#endif // FEAT_164_MQH
