// feat_010.mqh  — hma_20
// Auto-generated by gen_feat_mqh.py  (feature index 10)
// Python: features.py BASE_FEATURE_COLS[10] = "hma_20"
#ifndef FEAT_010_MQH
#define FEAT_010_MQH



double CalcFeat_010(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   // HMA(20) = WMA(2*WMA(10)-WMA(20), sqrt(20))
   double num_h=0,den_h=0, num_f=0,den_f=0;
   for(int k=0;k<10&&i+k<needed;k++){double w=10-k; num_h+=close[i+k]*w; den_h+=w;}
   for(int k=0;k<20&&i+k<needed;k++){double w=20-k; num_f+=close[i+k]*w; den_f+=w;}
   double wma_half=(den_h>0)?num_h/den_h:close[i];
   double wma_full=(den_f>0)?num_f/den_f:close[i];
   double diff_val = 2.0*wma_half - wma_full;
   // WMA(diff, 4): need series of diff at i+0..i+3
   double num_s=0,den_s=0;
   for(int k=0;k<4&&i+k<needed;k++){
      double nh=0,dh=0,nf=0,df=0;
      for(int j=0;j<10&&i+k+j<needed;j++){double w=10-j;nh+=close[i+k+j]*w;dh+=w;}
      for(int j=0;j<20&&i+k+j<needed;j++){double w=20-j;nf+=close[i+k+j]*w;df+=w;}
      double dv=2.0*(dh>0?nh/dh:close[i+k])-(df>0?nf/df:close[i+k]);
      double w=4-k; num_s+=dv*w; den_s+=w;
   }
   return (den_s>0)?num_s/den_s:diff_val;
}

#endif // FEAT_010_MQH
