// feat_110.mqh  — lh
// Auto-generated by gen_feat_mqh.py  (feature index 110)
// Python: features.py BASE_FEATURE_COLS[110] = "lh"
#ifndef FEAT_110_MQH
#define FEAT_110_MQH



double CalcFeat_110(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{
   return (i+1<needed&&high[i]<high[i+1])?1.0:0.0;
}

#endif // FEAT_110_MQH
