// feat_123.mqh  — hour_sin
// Auto-generated by gen_feat_mqh.py  (feature index 123)
// Python: features.py BASE_FEATURE_COLS[123] = "hour_sin"
#ifndef FEAT_123_MQH
#define FEAT_123_MQH

// Requires GetBarTime(int i) defined in main EA

double CalcFeat_123(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   MqlDateTime mdt; TimeToStruct(GetBarTime(i),mdt);
   int hr=mdt.hour;
   
   return MathSin(2.0*M_PI*hr/24.0);
   
   
   
   
   
   
   
}

#endif // FEAT_123_MQH
