// feat_144.mqh  — ret5_25
// Auto-generated by gen_feat_mqh.py  (feature index 144)
// Python: features.py BASE_FEATURE_COLS[144] = "ret5_25"
#ifndef FEAT_144_MQH
#define FEAT_144_MQH



double CalcFeat_144(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+5<needed)?close[i+5]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_144_MQH
