// feat_163.mqh  — price_diff_5
// Auto-generated by gen_feat_mqh.py  (feature index 163)
// Python: features.py BASE_FEATURE_COLS[163] = "price_diff_5"
#ifndef FEAT_163_MQH
#define FEAT_163_MQH



double CalcFeat_163(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+5<needed)?close[i]-close[i+5]:0.0;
}

#endif // FEAT_163_MQH
