// feat_060.mqh  — wr_28
// Auto-generated by gen_feat_mqh.py  (feature index 60)
// Python: features.py BASE_FEATURE_COLS[60] = "wr_28"
#ifndef FEAT_060_MQH
#define FEAT_060_MQH



double CalcFeat_060(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double hi_p=high[i],lo_p=low[i];
   for(int k=1;k<28&&i+k<needed;k++){hi_p=MathMax(hi_p,high[i+k]);lo_p=MathMin(lo_p,low[i+k]);}
   return -100*(hi_p-close[i])/(hi_p-lo_p+1e-9)/100.0+0.5;
}

#endif // FEAT_060_MQH
