// feat_034.mqh  — stoch_d_14_3
// Auto-generated by gen_feat_mqh.py  (feature index 34)
// Python: features.py BASE_FEATURE_COLS[34] = "stoch_d_14_3"
#ifndef FEAT_034_MQH
#define FEAT_034_MQH



double CalcFeat_034(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   // Stoch(14,3) d
   // fast K
   double hi=high[i],lo_val=low[i];
   for(int k=1;k<14&&i+k<needed;k++){hi=MathMax(hi,high[i+k]);lo_val=MathMin(lo_val,low[i+k]);}
   double fk=(close[i]-lo_val)/(hi-lo_val+1e-9);
   double sk[3+1]; int sc2=0;
   for(int j=0;j<3&&i+j<needed;j++){
      double h2=high[i+j],l2=low[i+j];
      for(int k2=1;k2<14&&i+j+k2<needed;k2++){h2=MathMax(h2,high[i+j+k2]);l2=MathMin(l2,low[i+j+k2]);}
      double fk2=(close[i+j]-l2)/(h2-l2+1e-9);
      // smooth k
      double ssk=0; int ssc=0;
      for(int j2=0;j2<3&&i+j+j2<needed;j2++){
         double h3=high[i+j+j2],l3=low[i+j+j2];
         for(int k3=1;k3<14&&i+j+j2+k3<needed;k3++){h3=MathMax(h3,high[i+j+j2+k3]);l3=MathMin(l3,low[i+j+j2+k3]);}
         ssk+=(close[i+j+j2]-l3)/(h3-l3+1e-9); ssc++;
      }
      sk[j]=(ssc>0)?ssk/ssc:fk2; sc2++;
   }
   double sd=0; for(int j=0;j<sc2;j++) sd+=sk[j];
   return (sc2>0)?sd/sc2:fk;
}

#endif // FEAT_034_MQH
