// feat_155.mqh  — ret1_45
// Auto-generated by gen_feat_mqh.py  (feature index 155)
// Python: features.py BASE_FEATURE_COLS[155] = "ret1_45"
#ifndef FEAT_155_MQH
#define FEAT_155_MQH



double CalcFeat_155(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+45<needed)?close[i+45]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_155_MQH
