// feat_202.mqh  — price_diff_70
// Auto-generated by gen_feat_mqh.py  (feature index 202)
// Python: features.py BASE_FEATURE_COLS[202] = "price_diff_70"
#ifndef FEAT_202_MQH
#define FEAT_202_MQH



double CalcFeat_202(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+70<needed)?close[i]-close[i+70]:0.0;
}

#endif // FEAT_202_MQH
