// feat_136.mqh  — vol_10
// Auto-generated by gen_feat_mqh.py  (feature index 136)
// Python: features.py BASE_FEATURE_COLS[136] = "vol_10"
#ifndef FEAT_136_MQH
#define FEAT_136_MQH



double CalcFeat_136(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<10&&i+k<needed;k++){s+=vol[i+k];c2++;}
   return (c2>0)?s/c2:0;
}

#endif // FEAT_136_MQH
