// feat_208.mqh  — price_diff_80
// Auto-generated by gen_feat_mqh.py  (feature index 208)
// Python: features.py BASE_FEATURE_COLS[208] = "price_diff_80"
#ifndef FEAT_208_MQH
#define FEAT_208_MQH



double CalcFeat_208(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+80<needed)?close[i]-close[i+80]:0.0;
}

#endif // FEAT_208_MQH
