// feat_212.mqh  — momentum_90
// Auto-generated by gen_feat_mqh.py  (feature index 212)
// Python: features.py BASE_FEATURE_COLS[212] = "momentum_90"
#ifndef FEAT_212_MQH
#define FEAT_212_MQH



double CalcFeat_212(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+90<needed)?close[i]-close[i+90]:0.0;
}

#endif // FEAT_212_MQH
