// feat_220.mqh  — price_diff_100
// Auto-generated by gen_feat_mqh.py  (feature index 220)
// Python: features.py BASE_FEATURE_COLS[220] = "price_diff_100"
#ifndef FEAT_220_MQH
#define FEAT_220_MQH



double CalcFeat_220(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+100<needed)?close[i]-close[i+100]:0.0;
}

#endif // FEAT_220_MQH
