// feat_160.mqh  — vol_50
// Auto-generated by gen_feat_mqh.py  (feature index 160)
// Python: features.py BASE_FEATURE_COLS[160] = "vol_50"
#ifndef FEAT_160_MQH
#define FEAT_160_MQH



double CalcFeat_160(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double s=0; int c2=0;
   for(int k=0;k<50&&i+k<needed;k++){s+=vol[i+k];c2++;}
   return (c2>0)?s/c2:0;
}

#endif // FEAT_160_MQH
