// feat_035.mqh  — stoch_k_9_3
// Auto-generated by gen_feat_mqh.py  (feature index 35)
// Python: features.py BASE_FEATURE_COLS[35] = "stoch_k_9_3"
#ifndef FEAT_035_MQH
#define FEAT_035_MQH



double CalcFeat_035(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   // Stoch(9,3) k
   // fast K
   double hi=high[i],lo_val=low[i];
   for(int k=1;k<9&&i+k<needed;k++){hi=MathMax(hi,high[i+k]);lo_val=MathMin(lo_val,low[i+k]);}
   double fk=(close[i]-lo_val)/(hi-lo_val+1e-9);
   // smooth
   double sk=0; int sc=0;
   for(int j=0;j<3&&i+j<needed;j++){
      double h2=high[i+j],l2=low[i+j];
      for(int k2=1;k2<9&&i+j+k2<needed;k2++){h2=MathMax(h2,high[i+j+k2]);l2=MathMin(l2,low[i+j+k2]);}
      sk+=(close[i+j]-l2)/(h2-l2+1e-9); sc++;
   }
   return (sc>0)?sk/sc:fk;
}

#endif // FEAT_035_MQH
