// feat_050.mqh  — adx_14
// Auto-generated by gen_feat_mqh.py  (feature index 50)
// Python: features.py BASE_FEATURE_COLS[50] = "adx_14"
#ifndef FEAT_050_MQH
#define FEAT_050_MQH



double CalcFeat_050(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double alpha=1.0/14.0;
   double rm_tr=high[needed-1]-low[needed-1];
   double rm_pdm=0,rm_ndm=0;
   for(int k=needed-2;k>=i;k--){
      double hl=high[k]-low[k];
      double hpc=MathAbs(high[k]-close[k+1]);
      double lpc=MathAbs(low[k]-close[k+1]);
      double tr=MathMax(hl,MathMax(hpc,lpc));
      rm_tr=alpha*tr+(1-alpha)*rm_tr;
      double up_m=high[k]-high[k+1];
      double dn_m=low[k+1]-low[k];
      double pdm=(up_m>dn_m&&up_m>0)?up_m:0.0;
      double ndm=(dn_m>up_m&&dn_m>0)?dn_m:0.0;
      rm_pdm=alpha*pdm+(1-alpha)*rm_pdm;
      rm_ndm=alpha*ndm+(1-alpha)*rm_ndm;
   }
   double pdi=100*rm_pdm/(rm_tr+1e-9);
   double ndi=100*rm_ndm/(rm_tr+1e-9);
   double dx=100*MathAbs(pdi-ndi)/(pdi+ndi+1e-9);
   // ADX = RMA(dx) -- approximate with single pass value
   return dx/14.0;  // simplified approximation
}

#endif // FEAT_050_MQH
