// feat_012.mqh  — sma_50
// Auto-generated by gen_feat_mqh.py  (feature index 12)
// Python: features.py BASE_FEATURE_COLS[12] = "sma_50"
#ifndef FEAT_012_MQH
#define FEAT_012_MQH



double CalcFeat_012(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double sum = 0.0;
   int cnt = 0;
   for(int k = i; k < i + 50 && k < needed; k++) { sum += close[k]; cnt++; }
   return (cnt > 0) ? sum / cnt : close[i];
}

#endif // FEAT_012_MQH
