// feat_185.mqh  — momentum_45
// Auto-generated by gen_feat_mqh.py  (feature index 185)
// Python: features.py BASE_FEATURE_COLS[185] = "momentum_45"
#ifndef FEAT_185_MQH
#define FEAT_185_MQH



double CalcFeat_185(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   return (i+45<needed)?close[i]-close[i+45]:0.0;
}

#endif // FEAT_185_MQH
