// feat_079.mqh  — ichi_senkou_a
// Auto-generated by gen_feat_mqh.py  (feature index 79)
// Python: features.py BASE_FEATURE_COLS[79] = "ichi_senkou_a"
#ifndef FEAT_079_MQH
#define FEAT_079_MQH



double CalcFeat_079(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double hi9=high[i],lo9=low[i]; for(int k=1;k<9&&i+k<needed;k++){hi9=MathMax(hi9,high[i+k]);lo9=MathMin(lo9,low[i+k]);}
   double tk=(hi9+lo9)/2.0;
   double hi26=high[i],lo26=low[i]; for(int k=1;k<26&&i+k<needed;k++){hi26=MathMax(hi26,high[i+k]);lo26=MathMin(lo26,low[i+k]);}
   double kj=(hi26+lo26)/2.0;
   return (tk+kj)/2.0;
}

#endif // FEAT_079_MQH
