// feat_099.mqh  — body
// Auto-generated by gen_feat_mqh.py  (feature index 99)
// Python: features.py BASE_FEATURE_COLS[99] = "body"
#ifndef FEAT_099_MQH
#define FEAT_099_MQH



double CalcFeat_099(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{
   return close[i]-open[i];
}

#endif // FEAT_099_MQH
