// feat_146.mqh  — ret1_30
// Auto-generated by gen_feat_mqh.py  (feature index 146)
// Python: features.py BASE_FEATURE_COLS[146] = "ret1_30"
#ifndef FEAT_146_MQH
#define FEAT_146_MQH



double CalcFeat_146(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double ref=(i+30<needed)?close[i+30]:close[needed-1];
   return (close[i]-ref)/(ref+1e-9);
}

#endif // FEAT_146_MQH
