// feat_047.mqh  — cci_7
// Auto-generated by gen_feat_mqh.py  (feature index 47)
// Python: features.py BASE_FEATURE_COLS[47] = "cci_7"
#ifndef FEAT_047_MQH
#define FEAT_047_MQH



double CalcFeat_047(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double tp=(high[i]+low[i]+close[i])/3.0;
   double s=0; int c2=7;
   for(int k=0;k<7&&i+k<needed;k++) s+=(high[i+k]+low[i+k]+close[i+k])/3.0;
   double m=s/c2;
   double mad=0;
   for(int k=0;k<7&&i+k<needed;k++) mad+=MathAbs((high[i+k]+low[i+k]+close[i+k])/3.0-m);
   mad/=c2;
   return (tp-m)/(0.015*mad+1e-9)/100.0;
}

#endif // FEAT_047_MQH
