// feat_102.mqh  — tr
// Auto-generated by gen_feat_mqh.py  (feature index 102)
// Python: features.py BASE_FEATURE_COLS[102] = "tr"
#ifndef FEAT_102_MQH
#define FEAT_102_MQH



double CalcFeat_102(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   double hl=high[i]-low[i];
   double hpc=(i+1<needed)?MathAbs(high[i]-close[i+1]):hl;
   double lpc=(i+1<needed)?MathAbs(low[i]-close[i+1]):hl;
   return MathMax(hl,MathMax(hpc,lpc));
}

#endif // FEAT_102_MQH
