// feat_021.mqh  — macdsig_12_26_9
// Auto-generated by gen_feat_mqh.py  (feature index 21)
// Python: features.py BASE_FEATURE_COLS[21] = "macdsig_12_26_9"
#ifndef FEAT_021_MQH
#define FEAT_021_MQH



double CalcFeat_021(
   const double &close[], const double &high[],
   const double &low[],  const double &open[],
   const double &vol[],  const int needed, const int i)
{

   // MACD(12,26,9) sig
   double af=0.15384615384615385, as_=0.07407407407407407, asig=0.2;
   double ef=close[needed-1], es=close[needed-1];
   for(int k=needed-2;k>=i;k--){ef=af*close[k]+(1-af)*ef; es=as_*close[k]+(1-as_)*es;}
   double ml=ef-es;
   // sig: need series of macd_line values back sig bars
   double sig_val=ml;
   // approx: run EMA of macd_line over full series
   double ef2=close[needed-1], es2=close[needed-1], prev_ml=0, sv=0;
   int first=1;
   for(int k=needed-2;k>=i;k--){
      ef2=af*close[k]+(1-af)*ef2; es2=as_*close[k]+(1-as_)*es2;
      double cur_ml=ef2-es2;
      if(first){sv=cur_ml;first=0;} else sv=asig*cur_ml+(1-asig)*sv;
   }
   sig_val=sv;
   return sig_val;
}

#endif // FEAT_021_MQH
